Tweak die function

diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -11,12 +11,13 @@ declare -Ar color=(
 
 die() {
     local ecode=EMISC
-    if [[ $1 =~ ^[0-9]+ ]] ; then
+
+    if [[ $1 =~ ^E[A-Z]+ ]] ; then
         ecode=$1
         shift
     fi
 
-    echo -e "${color[error]}E:${color[reset]} $BASH_LINENO: $ecode $@" >&2
+    echo -e "${color[error]}E:=$ecode=${color[reset]} $BASH_LINENO: $@" >&2
     exit ${ERROR[ecode]}
 }
 
